/*
 * Swagger Car automotive
 * Sample for an Automotive.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: juanpablo.rivera@globant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Client;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientApi
 */
@Ignore
public class ClientApiTest {

    private final ClientApi api = new ClientApi();

    
    /**
     * Create client
     *
     * This can only be done by the logged in client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createClientTest() throws ApiException {
        Client body = null;
        api.createClient(body);

        // TODO: test validations
    }
    
    /**
     * Creates list of clients with given input array
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createClientsWithArrayInputTest() throws ApiException {
        List<Client> body = null;
        api.createClientsWithArrayInput(body);

        // TODO: test validations
    }
    
    /**
     * Creates list of clients with given input array
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createClientsWithListInputTest() throws ApiException {
        List<Client> body = null;
        api.createClientsWithListInput(body);

        // TODO: test validations
    }
    
    /**
     * Delete client
     *
     * This can only be done by the logged in client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClientTest() throws ApiException {
        String clientname = null;
        api.deleteClient(clientname);

        // TODO: test validations
    }
    
    /**
     * Get client by client name
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClientByNameTest() throws ApiException {
        String clientname = null;
        Client response = api.getClientByName(clientname);

        // TODO: test validations
    }
    
    /**
     * Logs client into the system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginClientTest() throws ApiException {
        String clientname = null;
        String password = null;
        String response = api.loginClient(clientname, password);

        // TODO: test validations
    }
    
    /**
     * Logs out current logged in client session
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logoutClientTest() throws ApiException {
        api.logoutClient();

        // TODO: test validations
    }
    
    /**
     * Updated client
     *
     * This can only be done by the logged in client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClientTest() throws ApiException {
        String clientname = null;
        Client body = null;
        api.updateClient(clientname, body);

        // TODO: test validations
    }
    
}
